name: Update website

# Update on every push
on: [push]

jobs:
  build:
    name: Update website
    runs-on: ubuntu-latest
    steps:
      # check-out this repository
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Set up pandoc
        uses: r-lib/actions/setup-pandoc@v1
    - name: Install LaTeX
      shell: bash -l {0}
      run: |
          sudo paperconfig -p letter
          sudo apt-get install -qq --no-install-recommends dvipng texlive-latex-base texlive-latex-extra texlive-fonts-recommended graphviz xzdec
      - name: Install dependencies
        shell: bash -l {0}
        working-directory: notes
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      # Check that all links work
      - name: Check external links
        shell: bash -l {0}
        working-directory: notes
        run: make linkcheck
      # Build the website locally
      - name: Build website
        shell: bash -l {0}
        working-directory: notes
        run: make html
      # Setup SSH agent
      - uses: webfactory/ssh-agent@v0.2.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      # Upload to lepus
      - name: Upload
        shell: bash -l {0}
        working-directory: notes
        run: rsync -e"ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" -azv build/html/ bovy@lepus.astro.utoronto.ca:/home/bovy/web/codepackagingminicourse/notes/
